### ISSUE TITLE
Lungs outline and details

### ISSUE THREAD

**Issue by popular1119** [rongqing-chen/DCT-EIT#2]
Dear blogger, thank you very much for the electrical impedance tomography DCT algorithm information you uploaded on github, which allowed me to see a brand new algorithm. I downloaded the compressed package myself and ran the code on my computer, and everything went smoothly. But I have some questions, because the lung outline in your code comes from your own data. Now I need to use my own lung CT to obtain the details and outline of my own lungs. What should I do? Because different lung CTs will change some values, such as p, q, T, K, etc. So it's very important, because you are the original, so your accomplishments in this area are far better than mine. 
If you have time, please help me answer my doubts. Thank you very much. In addition, the New Year is approaching. I wish you all the best in 2024.

**Comment by rongqing-chen** [comment]
Hi there, p and q are frequencies chosen to generate a subset of the DCT basis function. This should be selected based on your interest, such as the desired degrees of freedom in your inverse problem. The calculation of the T mapping is quite well described in the function [cal_mapping.m]. I suggest you read the published manuscript: _https://doi.org/10.1371/journal.pone.0285619_. Thanks for your interest in this algorithm.
